# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0005_auto_20160329_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 15, 5, 31, 940708)),
            preserve_default=False,
        ),
    ]
